# This is a basic workflow that is manually triggered

name: Build all Docker images

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [main]

  pull_request:
    branches: [main]
    
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  linux:

    strategy:
      fail-fast: false
      matrix:
       runner:
         - ubuntu-latest
         - ubuntu-24.04-arm
  
    # The type of runner that the job will run on
    runs-on: ${{ matrix.runner }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Git Checkout
      uses: actions/checkout@v4.2.2
    
    # Runs a single command using the runners shell
    - name: linux-vcpkg-base
      shell: sh
      working-directory: ./base-images/linux-amd64-vcpkg
      run: docker build --build-arg GITHUB_TOKEN=$GITHUB_TOKEN -t linux-vcpkg-base .

    - name: linux-vcpkg-qt6
      shell: sh
      working-directory: ./qt/linux-amd64-vcpkg-qt6
      run: docker build --build-arg GITHUB_TOKEN=$GITHUB_TOKEN -t linux-vcpkg-qt6 .

  windows:

    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Git Checkout
      uses: actions/checkout@v4.2.2
    
    # Runs a single command using the runners shell
    - name: Docker Build
      shell: sh
      working-directory: ./base-images/win/WinServer-Amd64-Vcpkg-MSVC
      run: docker build --build-arg GITHUB_TOKEN=$GITHUB_TOKEN -t winserver-amd64-vcpkg-msvc-base .
